# Generated by Django 3.0.6 on 2020-05-18 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=25)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.Employees')),
            ],
        ),
    ]
