# Generated by Django 3.0.6 on 2020-05-18 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('BIOTECH', 'BIOTECH'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('MME', 'MME'), ('CHEM', 'CHEM'), ('SHM', 'SHM'), ('SOS', 'SOS'), ('Administration Section', 'Administration Section'), ('Admissions Section', 'Admissions Section'), ('Exam Section', 'Exam Section'), ('T&P Cell', 'T&P Cell'), ('Research Cell', 'Research Cell'), ('Planning & Development Section', 'Planning & Development Section'), ('Student Affairs Section', 'Student Affairs Section'), ('Financial Section', 'Financial Section'), ('Inventory Section', 'Inventory Section'), ('Sales & Purchases Section', 'Sales & Purchases Section'), ('Medical Section', 'Medical Section'), ('Boys Hostels', 'Boys Hostels'), ('Girls Hostels', 'Girls Hostels')], max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('specs', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('requirements', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prod_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Usable', 'Usable'), ('Maintenance', 'Maintenance'), ('Unusable', 'Unusable')], default='Usable', max_length=15)),
                ('branch', models.CharField(blank=True, choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('BIOTECH', 'BIOTECH'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('MME', 'MME'), ('CHEM', 'CHEM'), ('SHM', 'SHM'), ('SOS', 'SOS'), ('Administration Section', 'Administration Section'), ('Admissions Section', 'Admissions Section'), ('Exam Section', 'Exam Section'), ('T&P Cell', 'T&P Cell'), ('Research Cell', 'Research Cell'), ('Planning & Development Section', 'Planning & Development Section'), ('Student Affairs Section', 'Student Affairs Section'), ('Financial Section', 'Financial Section'), ('Inventory Section', 'Inventory Section'), ('Sales & Purchases Section', 'Sales & Purchases Section'), ('Medical Section', 'Medical Section'), ('Boys Hostels', 'Boys Hostels'), ('Girls Hostels', 'Girls Hostels')], max_length=100, null=True)),
                ('specs', models.TextField(blank=True, null=True)),
                ('update', models.TextField(blank=True, null=True)),
                ('room_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.Rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('BIOTECH', 'BIOTECH'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('MME', 'MME'), ('CHEM', 'CHEM'), ('SHM', 'SHM'), ('SOS', 'SOS'), ('Administration Section', 'Administration Section'), ('Admissions Section', 'Admissions Section'), ('Exam Section', 'Exam Section'), ('T&P Cell', 'T&P Cell'), ('Research Cell', 'Research Cell'), ('Planning & Development Section', 'Planning & Development Section'), ('Student Affairs Section', 'Student Affairs Section'), ('Financial Section', 'Financial Section'), ('Inventory Section', 'Inventory Section'), ('Sales & Purchases Section', 'Sales & Purchases Section'), ('Medical Section', 'Medical Section'), ('Boys Hostels', 'Boys Hostels'), ('Girls Hostels', 'Girls Hostels')], max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=50)),
                ('room_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.Rooms')),
            ],
        ),
    ]
