# Generated by Django 3.0.6 on 2020-05-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='name',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
