# Generated by Django 3.0.6 on 2020-05-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_rooms_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('BIOTECH', 'BIOTECH'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('MME', 'MME'), ('CHEM', 'CHEM'), ('SHM', 'SHM'), ('SOS', 'SOS'), ('Administration Section', 'Administration Section'), ('Admissions Section', 'Admissions Section'), ('Exam Section', 'Exam Section'), ('T&P Cell', 'T&P Cell'), ('Research Cell', 'Research Cell'), ('Planning & Development Section', 'Planning & Development Section'), ('Student Affairs Section', 'Student Affairs Section'), ('Financial Section', 'Financial Section'), ('Inventory Section', 'Inventory Section'), ('Sales & Purchases Section', 'Sales & Purchases Section'), ('Medical Section', 'Medical Section'), ('Boys Hostels', 'Boys Hostels'), ('Girls Hostels', 'Girls Hostels')], default='CSE', max_length=100),
            preserve_default=False,
        ),
    ]
