# Generated by Django 3.0.6 on 2020-05-18 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_rooms_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='room_id',
            new_name='room',
        ),
        migrations.AddField(
            model_name='requests',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.Rooms'),
        ),
    ]
