# Generated by Django 3.0.6 on 2020-05-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20200518_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('specs', models.TextField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('Computer Accessories', 'Computer Accessories'), ('Eletronics', 'Electronics'), ('Stationary', 'Stationary'), ('Sports', 'Sports'), ('Groceries', 'Groceries'), ('Chemicals', 'Chemicals'), ('Lavatory Products', 'Lavatory Products'), ('Lab Hardwares', 'Lab Hardwares'), ('Furnitures', 'Furnitures')], max_length=50)),
                ('count', models.IntegerField()),
                ('status', models.CharField(choices=[('To Buy', 'To Buy'), ('Processing', 'Processing'), ('Bought', 'Bought')], default='To Buy', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='kind',
            field=models.CharField(choices=[('Computer Accessories', 'Computer Accessories'), ('Eletronics', 'Electronics'), ('Stationary', 'Stationary'), ('Sports', 'Sports'), ('Groceries', 'Groceries'), ('Chemicals', 'Chemicals'), ('Lavatory Products', 'Lavatory Products'), ('Lab Hardwares', 'Lab Hardwares'), ('Furnitures', 'Furnitures')], default='Computer Accessories', max_length=50),
            preserve_default=False,
        ),
    ]
