# Generated by Django 3.0.6 on 2020-05-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_auto_20200519_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='kind',
            field=models.CharField(choices=[('Computer Accessories', 'Computer Accessories'), ('Eletronics', 'Electronics'), ('Stationary', 'Stationary'), ('Sports', 'Sports'), ('Groceries', 'Groceries'), ('Chemicals', 'Chemicals'), ('Lavatory Products', 'Lavatory Products'), ('Lab Hardwares', 'Lab Hardwares'), ('Furnitures', 'Furnitures')], default='Computer Accessories', max_length=50),
            preserve_default=False,
        ),
    ]
